# 1) create a 3*3*3 array with random values in python

In [1]:
import numpy as np


random_array = np.random.rand(3, 3, 3)


print(random_array)


[[[0.78964021 0.42335519 0.22545026]
  [0.73216534 0.14700623 0.1409757 ]
  [0.07151892 0.42498238 0.15453456]]

 [[0.50376576 0.34409229 0.98624135]
  [0.26315282 0.9492116  0.69659705]
  [0.50971886 0.59468141 0.83023457]]

 [[0.98138635 0.27363192 0.30784831]
  [0.87010833 0.22993862 0.14663071]
  [0.05374204 0.32527891 0.90212363]]]


# 2)create a 5*5 matrix with values 1,2,3,4 just below the diagonal


In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5), dtype=int)

# Set values 1, 2, 3, and 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

# Print the resulting matrix
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3)create a 8*8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            matrix[i, j] = 1

# Print the resulting matrix
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4)normalize a 5*5 random matrix

In [4]:
import numpy as np


random_matrix = np.random.rand(5, 5)


min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

normalized_matrix = (random_matrix - min_value) / (max_value - min_value)


print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.15270648 0.55083706 0.51143999 0.36925036 0.86242859]
 [0.30559906 0.6897741  0.3089943  0.62276227 0.56289975]
 [0.28267857 0.92850656 0.29473294 0.11587282 0.32918945]
 [0.13556656 0.72057024 0.46295233 0.02988493 0.53488838]
 [0.39210206 0.61322314 0.3914764  0.95442182 0.95891231]]

Normalized Matrix:
[[0.13220444 0.56075002 0.51834324 0.36529109 0.89614545]
 [0.29677718 0.7103011  0.3004318  0.63816993 0.57373424]
 [0.2721057  0.96727141 0.28508095 0.09255689 0.32216975]
 [0.11375513 0.74344989 0.46615138 0.         0.54358295]
 [0.38988853 0.62790206 0.38921509 0.99516645 1.        ]]


# 5) how to find common values between two array


In [5]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

common_values = [value for value in list1 if value in list2]

print(common_values)


[3, 4, 5]


In [6]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

set1 = set(list1)
set2 = set(list2)

common_values = list(set1.intersection(set2))

print(common_values)


[3, 4, 5]


# 6)how o get the dates of yesterday , today and tomorrow?


In [7]:
from datetime import datetime, timedelta


today = datetime.now().date()


yesterday = today - timedelta(days=1)


tomorrow = today + timedelta(days=1)


today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7)consider two random array A and B, check if they are equal?


In [9]:
import numpy as np


A = np.random.rand(5, 6)
B = np.random.rand(4, 5)


are_equal = np.array_equal(A, B)


if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8)create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np

random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

# Print the original and modified vector
print("Original Vector:")
print(random_vector)


Original Vector:
[0.58639155 0.         0.21593386 0.29625715 0.19854238 0.87905111
 0.26774322 0.51887512 0.41635512 0.7664935 ]


# 9)how to print all the values in array 

In [11]:
my_array = [ 4, 5,6,7,8]

# Using a for loop to print all values
for value in my_array:
    print(value)


4
5
6
7
8


# 10)subratct the mean of each row of matrix

In [12]:
import numpy as np

# Create a sample matrix
matrix = np.array([[11, 22, 33],
                   [44, 55, 66],
                   [77, 88, 99]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
matrix_normalized = matrix - row_means.reshape(-1, 1)

# Print the original and normalized matrices
print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(matrix_normalized)


Original Matrix:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Matrix with Row Means Subtracted:
[[-11.   0.  11.]
 [-11.   0.  11.]
 [-11.   0.  11.]]


# 11)consiser a given vector how to add 1 to each element indexed by a second vector( be careful with repeated indices)

In [13]:
import numpy as np


given_vector = np.array([1, 2, 3, 4, 5])


indices_to_increment = np.array([1, 3, 1, 4])


unique_indices = np.unique(indices_to_increment)


given_vector[unique_indices] += 1

print(given_vector)


[1 3 3 5 6]


# 12)how to get the diagonal of a dot product ?


In [14]:
import numpy as np

# Create two matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])


dot_product_matrix = np.dot(matrix_A, matrix_B)

diagonal_elements = np.diag(dot_product_matrix)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nDot Product Matrix:")
print(dot_product_matrix)

print("\nDiagonal Elements of Dot Product:")
print(diagonal_elements)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements of Dot Product:
[30 69 90]


# 13)how to find the most frequent valuse in an array?

In [15]:
from collections import Counter


my_array = [1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5]


element_counts = Counter(my_array)


most_common = element_counts.most_common()

most_frequent_value = most_common[0][0] 
frequency = most_common[0][1]


print("Most frequent value:", most_frequent_value)
print("Frequency:", frequency)


Most frequent value: 5
Frequency: 4


# 14) how to get the n largest values of an array

In [16]:
import numpy as np


my_array = np.array([4, 2, 8, 1, 6, 5, 7, 3])


n = 3


indices = np.argsort(my_array)[-n:]


n_largest_values = my_array[indices]


print("N largest values:", n_largest_values)


N largest values: [6 7 8]


# 15)how tp create a record array from a regular array

In [13]:
import numpy as np


data = [(11, 'ka', 22),
        (22, 'ma', 45),
        (33, 'li', 14)]

dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create a record array from the regular array
record_array = np.rec.array(data, dtype=dtype)

# Access elements in the record array by field names
print("Record Array:")
print(record_array)
print("\nAccessing elements:")
print("ID:", record_array.ID)
print("Name:", record_array.Name)
print("Age:", record_array.Age)

Record Array:
[(11, 'ka', 22) (22, 'ma', 45) (33, 'li', 14)]

Accessing elements:
ID: [11 22 33]
Name: ['ka' 'ma' 'li']
Age: [22 45 14]


# 16) how to swap two rows of an array?

In [4]:
import numpy as np

my_array = np.array([[11, 22, 33],
                     [44, 55, 66],
                     [77, 88, 99]])

row1_index = 0
row2_index = 1

my_array[row1_index], my_array[row2_index] = my_array[row2_index].copy(), my_array[row1_index].copy()


print("Array with Rows Swapped:")
print(my_array)


Array with Rows Swapped:
[[44 55 66]
 [11 22 33]
 [77 88 99]]


# 17)write a python code to reshape to the next dimension of numpy array

In [6]:
import numpy as np


original_array = np.array([1, 2, 3, 4, 5, 6])

current_shape = original_array.shape
new_shape = (current_shape[0], 1) 


reshaped_array = original_array.reshape(new_shape)


print("Original Array (1D):")
print(original_array)

print("\nReshaped Array (2D):")
print(reshaped_array)


Original Array (1D):
[1 2 3 4 5 6]

Reshaped Array (2D):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
18)